defaults: &defaults
  options:
    identity_map_enabled: true

development:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: 'ipress_dev'

test:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: 'ipress_test'

# set these environment variables on your prod server
production:
  <<: *defaults
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>